Use a spreadsheet as input file as an alternative to .py files
RAMP-project/RAMP pull request #34
Opened 2022-06-08 19:13 UTC by Bachibouzouk

Closes #29

2022-06-10 05:39 UTC, Bachibouzouk commented
The last thing I would like to add is an documentation of the parameters

2022-06-14 13:14 UTC, Bachibouzouk commented
@FLomb - it is ready for review

2022-06-14 14:25 UTC, FLomb commented
> @FLomb - it is ready for review

I'm going through it while testing it locally on my machine

2022-06-23 06:42 UTC, Bachibouzouk commented
@FLomb - Do you have an estimate when you would have time to review this PR?

2022-06-23 09:25 UTC, FLomb commented
@Bachibouzouk I have already started reviewing and making some comments; I'll keep going with the rest as soon as other deadlines allow. We might also have some more people joining the process in the coming days. Have you had a look at the comments made so far?

2022-06-23 10:53 UTC, Bachibouzouk commented
> Have you had a look at the comments made so far?

I don't see any comments, were did you comment?

2022-06-23 10:57 UTC, FLomb requested changes

2022-06-23 10:59 UTC, FLomb commented
> > Have you had a look at the comments made so far?
> 
> @FLomb I don't see any comments, were did you comment? Maybe you need to click on the "Submit your review" button

You're right, I had it saved as a draft because I was planning to keep going asap. I've now submitted these preliminary comments.

2022-06-23 10:59 UTC, Bachibouzouk commented on requirements.txt
> +openpyxl
I prefer to have a .txt file for requirements because one can refer to it in the requirements.yml file as well, thus enabling 2 ways (pip or conde) instead of one (only conda)

2022-06-23 11:05 UTC, Bachibouzouk commented on docs/input_parameters.md
> +TODO: specify difference between xlsx and python input (future also pack the windows param in the add, appliance method)
I guess I forgot to delete it ...

2022-06-24 08:25 UTC, FLomb commented on requirements.txt
> +openpyxl
Ok cool, then could you modify it in such a way that both ways work (e.g. referring to the .txt file in the .yml)?

2022-06-24 21:05 UTC, Bachibouzouk commented on requirements.txt
> +openpyxl
Yes I will do it

2022-06-29 10:55 UTC, Bachibouzouk commented on requirements.txt
> +openpyxl
Done in b6cd817e0a1178d1ca5fef8c5748ccc306272f0f

2022-06-29 11:30 UTC, Bachibouzouk commented on ramp/ramp_run.py
> +
Done in  a094edf87967be2c39b9b91064c263f1e1399baa

2022-06-29 11:37 UTC, Bachibouzouk commented
@FLomb - I made changes according to what you asked, can you let me know if you are now satisfied ?

2022-07-08 13:29 UTC, FLomb commented on README.md
> +To get started, download the repository, install the dependencies with `pip install -r requirements.txt`, move to the `ramp` folder and simply run the `python ramp_run.py`. The console will ask how m
Let's mention also the option to install via conda and .yml file now that we have it.

2022-07-08 13:38 UTC, merged