Add RTD Documentation
RAMP-project/RAMP pull request #51
Opened 2022-11-11 12:23 UTC by Bachibouzouk

2022-11-11 12:40 UTC, Bachibouzouk commented on README.rst
> +  pip install ramp
`pip install ramp` will not install this package but

https://pypi.org/project/ramp/

2022-11-11 12:40 UTC, Bachibouzouk commented on README.rst
> +  pip install ramp
If you want to install the local package one can `pip install -e .` when being at the root of the repository

2022-11-11 12:47 UTC, Bachibouzouk commented on README.rst
> +   radio = low_income_household.Appliance(
```suggestion
   radio = low_income_household.add_appliance(
```
`.Appliance` should only be used for back-compatibility and `.add_appliance` should be preferred

2022-11-11 12:51 UTC, Bachibouzouk commented
I suggest we focus on commenting what is not working in the proposed version in this PR and that we postpone changes of structure or addition of explanation in subsequent PR, otherwise we might end up spending a lot of time merging this PR. I know a way to automatically generate the readthedocs online upon pushing commits, I could set that up (I will see if I have enough rights for that)

2022-11-17 15:05 UTC, FLomb commented
> To build the documentation locally:
> 
> 1. create/activate your virtual environment
> 2. move to the `docs` folder with `cd docs`
> 3. install the doc dependencies (only have to do it once): `pip install -r docs-requirements.txt`
> 4. build the documentation locally: `make html` (you can then in your file explorer open the file `docs/build/html/index.html` which should automatically open in your favorite browser)

This works for me, but it is worth mentioning that I end up with two warnings in the process. See below:
```
/home/fl/GitHub-repos/RAMP/ramp/core/core.py:docstring of ramp.core.core.Appliance.specific_cycle:12: WARNING: Inline strong start-string without end-string.
/home/fl/GitHub-repos/RAMP/docs/source/examples/using_excel/using_excel.rst:229: WARNING: image file not readable: examples/using_excel/excel_file.png
```
I guess this affects what I see in a couple of pages of the docs. Other than this, I have a few comments about the contents and the structure which I will provide where/when needed

2022-11-17 15:22 UTC, FLomb requested changes
Thanks for kick-starting these docs, it's great to finally have something professional!

There are a number of content-related issues to fix before merging. In general, the landing page should contain less information and redirect more to the other pages where more details can be found.

The new example notebooks are very useful, but they need to be put into context. How do they relate to the example input files? (which are, incidentally, missing from the docs, whilst they should be there)

2022-11-17 15:22 UTC, FLomb commented on README.rst
> +2. If you create a new environment for mario, to use it, you need to activate the ramp environment each time by writing
there is a reference to 'mario' here which I guess is a typo

2022-11-17 15:22 UTC, FLomb commented on README.rst
> +To get conda, `download and install "Anaconda Distribution" <https://www.anaconda.com/products/individual>`_.
Perhaps we should also point to miniconda, which is lighter

2022-11-17 15:22 UTC, FLomb commented on README.rst
> +Installing throguh source code
How?

2022-11-17 15:22 UTC, FLomb commented on README.rst
> +Installing through conda
Why missing? we already had text about how to install via conda in the development branch

2022-11-17 15:22 UTC, FLomb commented on README.rst
> +RAMP has been tested on macOS and Windows.
And Linux too

2022-11-17 15:22 UTC, FLomb commented on README.rst
> +#. A number of Python adds-on packages
Why don't we have the specific packages' names anymore? If we don't want to list them here, we should at least point to where they can be found

2022-11-17 15:22 UTC, FLomb commented on README.rst
> +#. RAMP software itself
I would say this is redundant, isn't it?

2022-11-17 15:22 UTC, FLomb commented on README.rst
> +How to create a user category?
I don't think it's ideal to begin the 'Quick start' with user categories. What does even 'user category' mean to someone who lends on this page for the first time? 

We need to start from the broader context, as we do in the development branch. Why is all that text gone? Starting from a broader and simple walkthrough, we can then point users to more detailed examples to be found in the docs.

2022-11-17 15:22 UTC, FLomb commented on README.rst
> +Some of the key packages that RAMP relies on are:
Ok, we already mention some vague (see my comment above) requirements in lines 72-73. Why do we repeat the requirements here, but now in a more expanded fashion? And why are they still less than those listed in the development branch?

2022-11-17 15:22 UTC, FLomb commented on README.rst
> +List of publications
This is now on the website, so we can get rid of it and instead point users to the website.
In general, we should make sure that both the website and the Gitter chat are shown in a prominent position at the top of this README file

2022-11-17 15:22 UTC, FLomb commented on ramp/core/constants.py
> +            #"p_series",
what's going on here?

2022-11-17 15:39 UTC, mohammadamint commented on README.rst
> +  pip install ramp
> `pip install ramp` will not install this package but
> 
> https://pypi.org/project/ramp/

Sure. Just put at as a template to be filled correctly once we have ramp uploaded on pypi.

2022-11-17 15:56 UTC, mohammadamint commented on README.rst
> +Installing throguh source code
Will be added.

2022-11-17 15:58 UTC, mohammadamint commented on README.rst
> +Installing through conda
more than installing through the txt file, we may consider publish it on conda-forge

2022-11-17 15:59 UTC, mohammadamint commented on README.rst
> +#. A number of Python adds-on packages
We may merge this part and python requirements into one section.

2022-11-17 16:00 UTC, mohammadamint commented on README.rst
> +How to create a user category?
> I don't think it's ideal to begin the 'Quick start' with user categories. What does even 'user category' mean to someone who lends on this page for the first time?
> 
> We need to start from the broader context, as we do in the development branch. Why is all that text gone? Starting from a broader and simple walkthrough, we can then point users to more detailed examples to be found in the docs.

Makes sense. I will merge this new quick start with the previous version of README to provide a better understanding of the context.

2022-11-17 16:02 UTC, mohammadamint commented on README.rst
> +List of publications
> 

Good idea. I will make sure that all the badges (gitter, pypi, conda, docs, website,...) will be position at the top of the readme file.

2022-11-24 13:26 UTC, Bachibouzouk commented on docs/source/examples.rst
> +======================================
```suggestion
RAMP examples
=============
```
The line under the title should have the same character length as the text

2022-11-24 13:34 UTC, Bachibouzouk commented
We might want to double check the structure of the docs (section, subsection etc) to make sure we use the syntax in the correct steps
https://raw.githubusercontent.com/readthedocs/sphinx_rtd_theme/f854c890e1445b99a43ac5f10463a5df83739a2e/docs/demo/structure.rst

Another project I worked on, where we spent quite some time on the structure could help for inspiration
https://github.com/rl-institut/multi-vector-simulator/tree/dev/docs for the source and https://multi-vector-simulator.readthedocs.io/en/latest/index.html for the result

2022-11-24 13:50 UTC, Bachibouzouk commented
The RAMP website url should be found on the landing docs page

2022-11-24 13:53 UTC, Bachibouzouk commented
https://pyvideo.org/write-the-docs-2016/write-the-readable-readme.html could be a nice inspiration :)

2022-11-24 14:08 UTC, Bachibouzouk commented
By using `entry_points` in `setup.py` one can then run ramp from the command line from anywhere 

```
entry_points={  # Optional
    "console_scripts": [
        "ramp=ramp.cli:main",
    ],
},
``` 

I only moved the file `ramp.py` into the `ramp/` folder, renamed it `cli.py` and moved the code which was under `if __name__ == "__main__":` to a function called `main()`

Then after I reinstall ramp locally `pip install -e .` I can then run very simply `ramp -i <path to input file> ` instead of `python ramp.py -i <path to input file>` (which I could only run from the root of this repository anyway)

2022-11-24 14:16 UTC, Bachibouzouk commented
https://github.com/rl-institut/super-repo/issues/8 could also be used for inspiration of readme file

2022-11-24 14:19 UTC, mohammadamint commented
> By using `entry_points` in `setup.py` one can then run ramp from the command line from anywhere
> 
> ```
> entry_points={  # Optional
>     "console_scripts": [
>         "ramp=ramp.cli:main",
>     ],
> },
> ```
> 
> I only moved the file `ramp.py` into the `ramp/` folder, renamed it `cli.py` and moved the code which was under `if __name__ == "__main__":` to a function called `main()`
> 
> Then after I reinstall ramp locally `pip install -e .` I can then run very simply `ramp -i <path to input file> ` instead of `python ramp.py -i <path to input file>` (which I could only run from the root of this repository anyway)
> 
> I can push this as commits on this PR or add it once it is merged so we avoid potential conflicts

Thanks for making my work easier!

2022-11-25 10:54 UTC, mohammadamint commented on README.rst
> +Some of the key packages that RAMP relies on are:
I avoided the repetition in the new series of commits.

Regarding having less dependencies listed here with respect to development branch, as math and random are built in python packages, I avoided mentioning them explicitly as dependencies.

2022-11-25 21:17 UTC, Bachibouzouk commented on Pipfile
> +ramp = {editable = true, path = "."}
Isn't it rampdemand here as well?

2022-11-28 10:26 UTC, Bachibouzouk commented
@mohammadamint - when do you think you will merge this pull request?

2023-01-15 22:34 UTC, merged